# Generated by Django 5.1.5 on 2025-01-29 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_issueout'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueout',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issueout_quantity', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='issueout',
            name='inventoryItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issueout_inventory', to='inventory.inventoryitem'),
        ),
    ]
