# Generated by Django 5.1.5 on 2025-01-31 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_issueout_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='issue_out_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='inventory.issueout'),
        ),
        migrations.AddField(
            model_name='issueout',
            name='issue_out_status',
            field=models.BooleanField(default=False),
        ),
    ]
